# -----------------------------------------------------
# Window rules
# -----------------------------------------------------

# Tiling rules
windowrule {
    name = edge-tile
    match:title = ^(Microsoft-edge)$
    tile = on
}

windowrule {
    name = brave-tile
    match:title = ^(Brave-browser)$
    tile = on
}

windowrule {
    name = chromium-tile
    match:title = ^(Chromium)$
    tile = on
}

# Floating windows
windowrule {
    name = pavucontrol-float
    match:title = ^(pavucontrol)$
    float = on
}

windowrule {
    name = blueman-float
    match:title = ^(blueman-manager)$
    float = on
}

windowrule {
    name = nm-connection-float
    match:title = ^(nm-connection-editor)$
    float = on
}

windowrule {
    name = qalculate-float
    match:title = ^(qalculate-gtk)$
    float = on
}

# Browser Picture in Picture
windowrule {
    name = pip-settings
    match:title = ^(Picture-in-Picture)$
    float = on
    pin = on
    move = 69.5% 4%
}

# Idle inhibit for fullscreen windows
# windowrule {
#     name = fullscreen-idleinhibit
#     match:fullscreen = 1
#     idleinhibit = fullscreen
# }
