# Royal
# background            #100814
# foreground            #504868
# cursor                #514965
# selection_background  #1e1d2a
# color0                #241f2a
# color8                #312d3c
# color1                #90274b
# color9                #d4346c
# color2                #23801c
# color10               #2cd845
# color3                #b49d27
# color11               #fde83a
# color4                #6480af
# color12               #8fb9f9
# color5                #664d96
# color13               #a479e2
# color6                #8aaabd
# color14               #abd3eb
# color7                #514965
# color15               #9d8bbd
# selection_foreground #100814
#
# Glacier
# background #0c1115
# foreground #ffffff
# cursor #6c6c6c
# selection_background #bd2523
# color0 #2e343c
# color8 #404a55
# color1 #bd0f2f
# color9 #bd0f2f
# color2 #35a770
# color10 #49e998
# color3 #fb9435
# color11 #fddf6e
# color4 #1f5872
# color12 #2a8bc1
# color5 #bd2523
# color13 #ea4727
# color6 #778397
# color14 #a0b6d3
# color7 #ffffff
# color15 #ffffff
# color16 #FF79C6
# selection_foreground #0c1115
#
#
#Floraverse
background            #0e0c15
foreground            #dbd0b9
cursor                #bbbbbb
selection_background  #f3e0b8
color0                #08002e
color8                #331d4c
color1                #64002c
color9                #cf2062
color2                #5d731a
color10               #b3ce58
color3                #cd751c
color11               #fac357
color4                #1d6da1
color12               #40a4cf
color5                #b7077e
color13               #f02aae
color6                #42a38c
color14               #62caa8
color7                #f3e0b8
color15               #fff5db
selection_foreground #0e0c15

#Dutone dark
# background            #1f1c27
# foreground            #b6a0ff
# cursor                #ff9738
# selection_background  #353146
# color0                #1f1c27
# color8                #353146
# color1                #d8393d
# color9                #d8393d
# color2                #2dcc72
# color10               #2dcc72
# color3                #d8b76e
# color11               #d8b76e
# color4                #ffc183
# color12               #ffc183
# color5                #dd8d40
# color13               #dd8d40
# color6                #2388ff
# color14               #2388ff
# color7                #b6a0ff
# color15               #e9e4ff
# color16 #FF79C6
# selection_foreground #1f1c27
#
# Argonaut
background            #0d0f18
foreground            #fffaf3
cursor                #ff0017
selection_background  #002a3a
color0                #222222
color8                #444444
color1                #ff000f
color9                #ff273f
color2                #8ce00a
color10               #abe05a
color3                #ffb900
color11               #ffd141
color4                #008df8
color12               #0092ff
color5                #6c43a5
color13               #9a5feb
color6                #00d7eb
color14               #67ffef
color7                #ffffff
color15               #ffffff
selection_foreground #0d0f18
