#    __ ___ __  __
#   / //_(_) /_/ /___ __
#  / ,< / / __/ __/ // /
# /_/|_/_/\__/\__/\_, /
#                /___/
#
# Configuration
font_family JetBrainsMono NFM Bold
# font_family                 CaskaydiaCove Nerd Font Mono
text_composition_strategy platform
disable_ligatures never
font_size                   11.5
adjust_line_height 145%
# modify_font 		baseline 1
bold_font                   auto
italic_font                 auto
bold_italic_font            auto
remember_window_size        no
initial_window_width        700
initial_window_height       1000
cursor_blink_interval       0.5
cursor_stop_blinking_after  1
scrollback_lines            2000
wheel_scroll_min_lines      1
enable_audio_bell           no
window_padding_width        2 1
hide_window_decorations     yes
background_opacity          0.90
dynamic_background_opacity  yes
confirm_os_window_close     0
# selection_foreground        none
# selection_background        none
# Include pywal colors
# include $HOME/.cache/wal/colors-kitty.conf
include $HOME/.config/kitty/current-theme.conf
# include $HOME/.config/kitty/rosepine.conf

# Include Custom Configuration
# Create the file custom.conf in ~/.config/kitty to overwrite the default configuration
include ./custom.conf
tab_bar_style custom
tab_bar_margin_width 0.0
tab_bar_margin_height 0.0 0.0
tab_bar_background none
tab_bar_min_tabs 1
tab_powerline_style angled
tab_activity_symbol none
tab_title_template "{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{title}"
active_tab_title_template none
tab_bar_min_tabs 1
tab_bar_style custom
tab_bar_background none
tab_bar_edge bottom


# -----------------------------
# Ghostty-like keybindings
# -----------------------------

# Basic window operations
map ctrl+c                 copy_to_clipboard
map ctrl+v                 paste_from_clipboard
map alt+r                  load_config_file
map alt+q                  close_window
map alt+n                  new_os_window

# Tab management
map alt+t                  new_tab
# map alt+l                  next_tab
# map alt+h                  previous_tab
map alt+comma              move_tab_backward
map alt+period             move_tab_forward

# Split windows
map alt+d                  launch --cwd=current --location=neighbor
# map alt+d                  launch --location=hsplit --height=200
map alt+u                  launch --vsplit
map ctrl+up                resize_window taller 10
map ctrl+down              resize_window shorter 10
map ctrl+left              resize_window narrower 10
map ctrl+right             resize_window wider 10
map super+e                resize_window reset
map alt+up                 neighboring_window up
map alt+down               neighboring_window down
map alt+left               neighboring_window left
map alt+right              neighboring_window right

map ctrl+shift+c           send_text all \x03

map alt+h send_text all \x1bh
map alt+j send_text all \x1bj
map alt+k send_text all \x1bk
map alt+l send_text all \x1bl

# BEGIN_KITTY_THEME
# Glacier
# include current-theme.conf
# END_KITTY_THEME
