preload = /home/rusty/Downloads/crab_catppuccin-latte-frappe-macchiato-mocha.png

wallpaper = eDP-1,/home/rusty/Downloads/crab_catppuccin-latte-frappe-macchiato-mocha.png
wallpaper = HDMI-A-1,/home/rusty/Downloads/crab_catppuccin-latte-frappe-macchiato-mocha.png

# Optional: Enable splash screen
splash = false

# Optional: Enable IPC for dynamic control
ipc = on
